
import os

# Create the base environment with the tool added and some
# suitable (optional) JINJA_ENVIRONMENT_VARS configured. 
# JINJA_ENVIRONMENT_VARS does not need to be set here. If required,
# it need only be set on each environment at *some point*.
env = Environment(ENV = {'PATH' : os.environ['PATH']},
        tools=['default', 'kicad'], 
        KICAD_ENVIRONMENT_VARS={'kibot': '../kibot.yaml'})

# A simple case
#nbconvert_env = env.Clone(NBCONVERT_CONTEXT={'passed_in_str': 'Passed in string'})
#env.preflight('shifter_report.json', os.path.join('shifter.pro'))
env.schema('shifter-main-schematic.pdf', os.path.join('shifter.pro'))
env.pcb('schifter_main_pcb.pdf', os.path.join('shifter.pro'))
env.gerbers('shifter_main_JLCPCB.zip', os.path.join('shifter.pro'))

# Now with templates in different directories
#jinja_env_2 = jinja_env.Clone(
#        JINJA_TEMPLATE_SEARCHPATH=[os.path.join('src', 'templates')])

#jinja_env_2.Jinja('another_rendered_templ.foo', 
#        os.path.join('src', 'additional_templates', 'an_includer.foo.jinja'))


# Try with a SConscript and a variant directory
#SConscript('src/SConscript', exports='jinja_env', variant_dir='variant_foo')
