import os

env = Environment(ENV = os.environ,
        tools=['default', 'kicad'], 
        KICAD_ENVIRONMENT_VARS={'pcb': {'libs': ['default']}})

for board in ['main', 'mount', 'panel'] :
    env.preflight('%s/kontur_%s_report.json' % (board,board), '%s/%s.pro' % (board,board))
    env.schema('%s/kontur_%s_schematic.pdf' % (board,board), '%s/%s.pro' % (board,board))
    env.pcb('%s/kontur_%s_pcb.svg' % (board,board), '%s/%s.pro' % (board,board))
    env.gerbers('%s/kontur_%s_JLCPCB.zip' % (board,board), '%s/%s.pro' % (board,board))
    env.bom('%s/kontur_%s_bom.json' % (board,board), '%s/%s.pro' % (board,board))

    Clean(os.path.join(board, '%s.pro' % board), os.path.join(board, 'fp-info-cache'))
    Clean(os.path.join(board, '%s.pro' % board), os.path.join(board, '%s-cache.lib' % board))
    Clean(os.path.join(board, '%s.pro' % board), Glob('%s/*-bak' % board)) 