import os

from SCons.Node import NodeList

env = Environment(ENV = os.environ,
        tools=['default', 'kicad'], 
        KICAD_ENVIRONMENT_VARS={'pcb': {'libs': ['default']}})
#env.Append(project_name='Default')

REPORTS = NodeList()

for board in ['main', 'mount', 'panel'] :
    REPORTS += env.preflight('%s/kontur_%s_report.json' % (board,board), '%s/%s.pro' % (board,board), project_name='kontur')
    env.schema('%s/kontur_%s_schematic.pdf' % (board,board), '%s/%s.pro' % (board,board))
    env.pcb('%s/kontur_%s_pcb.pdf' % (board,board), '%s/%s.pro' % (board,board))
    env.gerbers('%s/kontur_%s_JLCPCB.zip' % (board,board), '%s/%s.pro' % (board,board))
    REPORTS += env.bom('%s/kontur_%s_bom.json' % (board,board), '%s/%s.pro' % (board,board), project_name='kontur')

    Clean(os.path.join(board, '%s.pro' % board), os.path.join(board, 'fp-info-cache'))
    Clean(os.path.join(board, '%s.pro' % board), os.path.join(board, '%s-cache.lib' % board))
    Clean(os.path.join(board, '%s.pro' % board), Glob('%s/*-bak' % board)) 

env.reports('kontur_reports.json', REPORTS)
env.report2xunit('kontur_reports.xml', 'kontur_reports.json')